source 'https://rubygems.org'
gem 'unidecode'
gem 'thor'
gem 'sequel'
gem 'mysql2'
gem 'jekyll'
gem 'htmlentities'
gem 'hpricot'
gem 'nokogiri'
gem 'jekyll-import', :git => "https://github.com/jekyll/jekyll-import.git"